# Development application environment

---
apiVersion: v1
kind: Namespace
metadata:
  name: tail-spin-development
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tail-spin-development
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://rism.visualstudio.com/ARO%20Demo/_git/tailspin-argocd-cd
    targetRevision: main
    path: overlays/development
  destination:
    namespace: tail-spin-development
    server: https://kubernetes.default.svc